name: Build

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: Set up nix and IOHK cache
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: mlabs
          authToken: "${{ secrets.CACHIXKEY }}"
      - name: Build all project components
        run: nix build -L .#check.x86_64-linux
      - name: Setup environment for integral tests
        working-directory: ./test-env/ogmios-datum-cache-integral-tests
        run: docker-compose up -d
      - name: Integral tests
        run: nix develop -c cabal run ogmios-datum-cache-test
